### PR TITLE
Make project Python2 compatible

### PR DESCRIPTION
**Pull request by Jorl17**
This simple commit performs syntax changes to make the project work in Python 2. This is fully backwards compatible.

EDIT: Made a second commit removing an unnecessary pprint import

### CODE REVIEW

**Comment by Jorl17** [comment]
Hi!

Well, it is your call. At our company many projects are still stuck with legacy code based on python 2, and I believe that there may be others in such a situation. I belive that even after Django drops its support for security backwards into python 2, a lot of legacy code will be stuck in Python 2 and it will be hard for companies to port due to the changes required (mainly regarding string handling).

My personal opinion is that I would accept this pull request but not make Python 2 support a required feature, leaving it as a "could have" instead of a "must have". This is because supporting python 2 could eventually become a hinderance, though at the moment it does not seem to be the case. I am also a great fan of python 3, but, alas, I am stuck with legacy code.

**Comment by Marviel** [comment]
Any update on this?

**Comment by Jorl17** [comment]
Hi! I agree with @apirobot, the suggested fix should be implemented, though this has not been an issue we have faced yet.

**Comment by Marviel** [comment]
@Jorl17 cool! I'm just looking to use this feature so I'm hoping to get this stabilized soon :)

**Pull request merged**
