### PR TITLE
Fix support for partial update

### PR DESCRIPTION
**Pull request by tjwalch**
Partial update is compromised if `resourcetype` is still required. It is also unnecessary to provide it as the serializer type can be determined from the instance being updated. This PR fixes this.

### CODE REVIEW

**Comment by tjwalch** [comment]
I could not run tests without first running `./manage.py migrate` to create migrations, the test runner did not create any tables and so naturally all tests failed. With migrations it worked.

**Comment by tjwalch** [comment]
Yes, With migrations it works, without every test fails with `django.db.utils.OperationalError: no such table: django_content_type`.

**Comment by tjwalch** [comment]
So I created migrations and pushed them. It is Django best practice anyway.

**Comment by michaelhays** [comment]
Anything keeping this from being merged? It'd be nice to be able to PATCH without including a `"resourcetype"` :)

**Comment by isik-kaplan** [comment]
@apirobot Hello, anything keeping this from merging? 

https://github.com/apirobot/django-rest-polymorphic/issues/22#issuecomment-605016792 I'm going to bet some folks here are willing to take the responsibility of at least helping you on maintaining this library. 

I could've used some features that would be *great* addition to this library but I'm afraid of opening a PR for instance, since the ones here are hanging.

**Comment by isik-kaplan** [comment]
@tjwalch Hey, can you check that? If not I'll check what's the problem and PR it again myself, thanks! 

@apirobot Thanks for the prompt reply, if @tjwalch is not around I'll take a look in couple of days.

**Comment by osousa** [comment]
Why wasn't this fix considered ?

It would be very nice not having to worry about the resourcetype field while updating.

**Comment by mattwedge** [comment]
Got a PR for this [here](https://github.com/apirobot/django-rest-polymorphic/pull/38) - the tests are passing locally but they're not running automatically in TravisCI - is there a trick to getting them to run?

**Comment by osousa** [comment]
> Got a PR for this [here](https://github.com/apirobot/django-rest-polymorphic/pull/38) - the tests are passing locally but they're not running automatically in TravisCI - is there a trick to getting them to run?

You added my  suggested changes?

If I recall correctly this PR didn't work without the suggested changes on my comment

**Comment by denisorehovsky** [comment]
This was fixed in another PR #38. Closing

**Pull request closed without merging**
